dist: trusty
sudo: required
language: node_js
node_js:
  - "7"
os:
  - osx
  - linux
addons:
  apt:
    packages:
    - rpm
    - fakeroot
before_install:
  # 2016-10: Apple doesn't include openssl any more because of security
  - if [ "$TRAVIS_OS_NAME" = osx ]; then brew install openssl; fi
  - if [ "$TRAVIS_OS_NAME" = osx ]; then export CPPFLAGS="-I/usr/local/opt/openssl/include"; fi
  - if [ "$TRAVIS_OS_NAME" = osx ]; then export LDFLAGS="-L/usr/local/opt/openssl/lib"; fi

install:
  - npm install -g electron-forge
  - npm install
script:
  - npm test

before_deploy:
  - if [ "$TRAVIS_OS_NAME" = osx ]; then chmod +x add-osx-cert.sh; fi
  - if [ "$TRAVIS_OS_NAME" = osx ]; then ./add-osx-cert.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      export CERTIFICATE_P12=Certificate.p12;
      echo $CERTIFICATE_OSX_P12 | base64 — decode > $CERTIFICATE_P12;
      export KEYCHAIN=build.keychain;
      security create-keychain -p mysecretpassword $KEYCHAIN;
      security default-keychain -s $KEYCHAIN;
      security unlock-keychain -p mysecretpassword $KEYCHAIN;
      security import $CERTIFICATE_P12 -k $KEYCHAIN -P $CERTIFICATE_PASSWORD -T /usr/bin/codesign;
      IDENTITY=security find-identity -v
      echo $IDENTITY
    fi


deploy:
  provider: script
  skip_cleanup: true
  script: electron-forge publish
  api_key: $GITHUB_TOKEN
  on:
    tags: true
