dist: trusty
sudo: required
language: node_js
node_js:
  - "7"
os:
  - osx
  - linux
addons:
  apt:
    packages:
    - rpm
    - fakeroot
before_install:
  # 2016-10: Apple doesn't include openssl any more because of security
  # problems openssl had. Manually specify path to includes/libs.
  - if [ "$TRAVIS_OS_NAME" = osx ]; then brew install openssl; fi
  - if [ "$TRAVIS_OS_NAME" = osx ]; then export CPPFLAGS="-I/usr/local/opt/openssl/include"; fi
  - if [ "$TRAVIS_OS_NAME" = osx ]; then export LDFLAGS="-L/usr/local/opt/openssl/lib"; fi

  - export KEY_CHAIN=build.keychain
  - export CERTIFICATE_P12=certificate.p12
  - echo $CERTIFICATE_OSX_P12 | base64 --decode > $CERTIFICATE_P12
  - security create-keychain -p travis $KEY_CHAIN
  - security default-keychain -s $KEY_CHAIN
  - security unlock-keychain -p travis $KEY_CHAIN
  - security import $CERTIFICATE_P12 -k $KEY_CHAIN -P $CERTIFICATE_PASSWORD -T /usr/bin/codesign;
  - security find-identity -v
  - security set-key-partition-list -S apple-tool:,apple: -s -k travis $KEY_CHAIN


install:
  - npm install -g electron-forge
  - npm install
script:
  - npm test
  - npm run make

after_script:
  - rm -fr *.p12

before_deploy:
  - if [ "$TRAVIS_OS_NAME" = osx ]; then chmod +x add-osx-cert.sh; fi
  #- if [ "$TRAVIS_OS_NAME" = osx ]; then ./add-osx-cert.sh; fi


deploy:
  provider: script
  skip_cleanup: true
  script: electron-forge publish
  on:
    tags: true
