platform:
  - x64

environment:
  GITHUB_TOKEN:
    secure: E4qaT3siPp/6JLtpXmRRfnQytPM1RZ+9ifyhBnxCHBetp2UYYUHZwKcu+PvQGZkz

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node Current x64
  - npm install npm -g
  - npm install -g electron-forge
  - npm install

deploy_script:
  - if ($env:APPVEYOR_REPO_TAG -ne "true") { return }
  - npm run publish

test: off
