platform:
  - x64

environment:
  GITHUB_TOKEN:
    secure: E4qaT3siPp/6JLtpXmRRfnQytPM1RZ+9ifyhBnxCHBetp2UYYUHZwKcu+PvQGZkz

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 7 x64
  - npm install npm -g
  - npm install -g electron-forge
  - npm install

build_script:
  - electron-forge publish

test: off

on:
  APPVEYOR_REPO_TAG: true
